# Generated by Django 2.2.4 on 2020-01-13 04:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_chat_comment_likedvideos_membership_message_rating_savedvideos_subscription_tag_usermembership_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='reviewer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
