# Generated by Django 2.2.4 on 2020-01-15 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200113_0452'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('slug', models.SlugField()),
                ('open_date', models.DateTimeField(blank=True, help_text='Date entries open', null=True, verbose_name='Starting Date')),
                ('close_date', models.DateTimeField(blank=True, help_text='Date entries close', null=True, verbose_name='Ending Date')),
                ('award_date', models.DateTimeField(blank=True, help_text='Date prizes are awarded', null=True, verbose_name='Award Date')),
                ('instant_win', models.BooleanField(default=False, verbose_name='Instant Win')),
                ('instant_win_odds', models.IntegerField(blank=True, help_text='1 in ____. Enter whole number', null=True, verbose_name='Instant Win Odds')),
                ('daily', models.BooleanField(default=False, help_text='A new winner can be won daily', verbose_name='Daily Prizes')),
            ],
            options={
                'verbose_name': 'Contest',
                'verbose_name_plural': 'Contests',
            },
        ),
        migrations.AlterField(
            model_name='membership',
            name='membership_type',
            field=models.CharField(choices=[('Premium Monthly', 'premium monthly'), ('Premium Yearly', 'premium yearly'), ('Free', 'free')], default='Free', max_length=30),
        ),
        migrations.AlterField(
            model_name='membership',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Prize')),
                ('description', models.TextField(default='', verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='contest/prizes', verbose_name='Image')),
                ('date_available', models.DateField(blank=True, help_text='Date that the prize is to be awarded', verbose_name='Date Prize is Available')),
                ('number_available', models.IntegerField(blank=True, default=1, verbose_name='Number Available')),
                ('contest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Contest')),
            ],
            options={
                'verbose_name': 'Prize',
                'verbose_name_plural': 'Prizes',
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=150, verbose_name='Email')),
                ('code', models.CharField(max_length=25, verbose_name='Code')),
                ('winner', models.BooleanField(default=False, verbose_name='Winner')),
                ('contest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Contest')),
                ('prize', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Prize')),
            ],
            options={
                'verbose_name': 'Entry',
                'verbose_name_plural': 'Entries',
            },
        ),
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='A code that has to be present at time of submission', max_length=100, verbose_name='Code')),
                ('contest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Contest')),
            ],
            options={
                'verbose_name': 'Code',
                'verbose_name_plural': 'Codes',
            },
        ),
    ]
