# Generated by Django 2.2.4 on 2020-01-15 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_contest_winner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('slug', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Pornstar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('slug', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='exclude_tags',
            field=models.ManyToManyField(blank=True, related_name='exclude_tags', to='core.Tag'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='favorite_tags',
            field=models.ManyToManyField(blank=True, related_name='favorite_tags', to='core.Tag'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='favorite_videos',
            field=models.ManyToManyField(blank=True, to='core.Video'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='follows',
            field=models.ManyToManyField(blank=True, related_name='followers', to='core.UserProfile'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='friends_with', to='core.UserProfile'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_uploader',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='location',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='orientation',
            field=models.CharField(max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='race',
            field=models.CharField(max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='exclude_categories',
            field=models.ManyToManyField(blank=True, related_name='exclude_tags', to='core.Category'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='exclude_pornstars',
            field=models.ManyToManyField(blank=True, related_name='exclude_tags', to='core.Pornstar'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='favorite_categories',
            field=models.ManyToManyField(blank=True, related_name='favorite_tags', to='core.Category'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='favorite_pornstars',
            field=models.ManyToManyField(blank=True, related_name='favorite_tags', to='core.Pornstar'),
        ),
    ]
