# Generated by Django 2.2.4 on 2020-01-15 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200115_0503'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='tokens',
            field=models.IntegerField(default=0),
        ),
    ]
