# Generated by Django 2.2.4 on 2020-01-15 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200115_0615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='code',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Code'),
        ),
    ]
