# Generated by Django 2.2.3 on 2020-01-19 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200115_0730'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='tokens',
            new_name='tickets',
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='categories'),
        ),
    ]
