# Generated by Django 2.2.4 on 2020-01-22 03:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200119_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
