from django.urls import path
from .views import (
    UserIDView,
    ItemListView,
    ItemDetailView,
    AddToCartView,
    OrderDetailView,
    OrderQuantityUpdateView,
    PaymentView,
    AddCouponView,
    CountryListView,
    AddressListView,
    AddressCreateView,
    AddressUpdateView,
    AddressDeleteView,
    OrderItemDeleteView,
    PaymentListView,
    OrderListView,
    MembershipListView,
    ContestListView,
    ContestDetailView,
    UpdateTickets,
    TicketDetailView,
    EntriesDetailView,
    EntryCreateView,
    VideoListView,
    VideoDetailView,
    UserDetailView
)

urlpatterns = [
    path('user-id/', UserIDView.as_view(), name='user-id'),
    path('countries/', CountryListView.as_view(), name='country-list'),
    path('addresses/', AddressListView.as_view(), name='address-list'),
    path('addresses/create/', AddressCreateView.as_view(), name='address-create'),
    path('addresses/<pk>/update/',
         AddressUpdateView.as_view(), name='address-update'),
    path('addresses/<pk>/delete/',
         AddressDeleteView.as_view(), name='address-delete'),
    path('products/', ItemListView.as_view(), name='product-list'),
    path('products/<slug>/', ItemDetailView.as_view(), name='product-detail'),
    path('add-to-cart/', AddToCartView.as_view(), name='add-to-cart'),
    path('order-summary/', OrderDetailView.as_view(), name='order-summary'),
    path('checkout/', PaymentView.as_view(), name='checkout'),
    path('add-coupon/', AddCouponView.as_view(), name='add-coupon'),
    path('order-items/<pk>/delete/',
         OrderItemDeleteView.as_view(), name='order-item-delete'),
    path('order-item/update-quantity/',
         OrderQuantityUpdateView.as_view(), name='order-item-update-quantity'),
    path('payments/', PaymentListView.as_view(), name='payment-list'),
    path('orders/', OrderListView.as_view(), name='order-list'),
    path('membership/', MembershipListView.as_view(), name='membership-list'),
    path('play/', ContestListView.as_view(), name='contest-list'),
    path('play/<slug>/', ContestDetailView.as_view(), name='contest-detail'),
    path('profile-summary/', TicketDetailView.as_view(), name='profile-summary'),
    path('entries/',
         EntriesDetailView.as_view(), name='entries-list'),
    path('entries/create/',
         EntryCreateView.as_view(), name='entries-create'),
    path('videos/',
         VideoListView.as_view(), name='video-list'),
    path('videos/<slug>/',
         VideoDetailView.as_view(), name='video-detail'),
    path('user/<username>/',
         UserDetailView.as_view(), name='user-detail'),
    path('infinite-api/', EntriesDetailView.as_view(), name='infinite-react')
]
